/* FILENAME: DEF.H
 * PROGRAMMER: RK2
 * PURPOSE: Default definitions.
 * LAST UPDATE: 06.06.2014
 */

#ifndef __DEF_H_
#define __DEF_H_

#pragma warning(disable: 4244 4305)

#include <windows.h>

#define MATH_PI 3.1415

/* Large integer data types */
typedef __int64 INT64;
typedef unsigned __int64 UINT64;

/* Common float point types */
typedef float FLT;
typedef double DBL;

#endif /* __DEF_H_ */

/* END OF 'DEF.H' FILE */
