/* FILENAME: UNITS.H
 * PROGRAMMER: RK2
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 08.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Cow Unit create function. */
rk2UNIT *RK2_CowUnitCreate( VOID );

/* Anim Info Unit create function. */
rk2UNIT *RK2_InfoUnitCreate( VOID );

/* Creating unit clock function. */
rk2UNIT *RK2_UnitClockCreate( VOID );


#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
